backend:
  name: github
  repo: idunacaligata/odonata
  branch: main
  base_url: https://decap-cms-github-oauth-api.odonata-auth.workers.dev
media_folder: static/img
public_folder: /img

collections:
  # ────────────────────────────────────────────────
  # Suborder
  # ────────────────────────────────────────────────
  - name: "suborders"
    label: "Suborders"
    folder: "content/suborders"
    create: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - label: "Suborder name"
        name: "title"
        widget: "string"
        required: true
        hint: "Scientific name, e.g. Anisoptera"
      - label: "Authority"
        name: "authority"
        widget: "string"
        required: true
      - label: "Common name"
        name: "common_name"
        widget: "string"
        required: true
      - { label: "Date", name: "date", widget: "datetime"}
      - { label: "Draft", name: "draft", widget: "boolean", default: true}